# Issue template configuration
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/torohash/neutryx-rust#readme
    about: Check the README for usage documentation and examples.
  - name: Discussions
    url: https://github.com/torohash/neutryx-rust/discussions
    about: Ask questions or discuss ideas in GitHub Discussions.
